version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  dockbeat:
    image: ingensi/dockbeat:latest #they have no fixed tags
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /opt/docker-elk/dockbeat/:/etc/dockbeat
    networks:
      - elk
    depends_on:
      - logstash 

  logspout:
    build:
      context: logspout/
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        ROUTE_URIS: "logstash://logstash:5000"
    networks:
      - elk
        #    - OMS
    depends_on:
      - logstash 

networks:
  default:
    external:
      name: OMS
  elk:
    driver: bridge
