version: '2'

services:

  elasticsearch:
    build:
      context: ./$PATH_OMS_DOGWATCH/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./$PATH_OMS_GLOBAL/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: ./$PATH_OMS_DOGWATCH/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./$PATH_OMS_DOGWATCH/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./$PATH_OMS_DOGWATCH/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./$PATH_OMS_DOGWATCH/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./$PATH_OMS_DOGWATCH/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.backend=kibana
      - traefik.frontend.rule=HostRegexp:{domain:kibana.[a-z0-9.]+}
      - traefik.frontend.priority=20
      - traefik.frontend.auth.basic=admin:$$2y$$05$$nO3b1XapOtAORGcLAwMmyenyrVU4xWuEk08nEwvmFRcABz1NSv4Xq

  dockbeat:
    image: ingensi/dockbeat:latest #they have no fixed tags
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./$PATH_OMS_DOGWATCH/dockbeat/:/etc/dockbeat
    networks:
      - elk
    depends_on:
      - logstash 

  logspout:
    build:
      context: ./$PATH_OMS_DOGWATCH/logspout/
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        ROUTE_URIS: "logstash://logstash:5000"
    networks:
      - elk
        #    - OMS
    depends_on:
      - logstash 

networks:
  default:
    external:
      name: OMS
  elk:
    driver: bridge
