metricbeat.modules:
#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "filesystem", "fsstat", "memory", "network", "process", "core", "diskio", "socket"]
  period: 10s
  enabled: true
  processes: ['.*']

  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 20s

shipper:
    tags: ["host:testing", "beat:metric"]

#    fields:
#       env: staging
  
output:
    elasticsearch: 
        hosts: ["elasticsearch:9200"]
#    logstash: 
#        hosts: ["logstash:5000"]

setup:
    kibana:
        host: "kibana:5601"
    dashboards:
        enabled: true

